# fly.toml app configuration file generated for shahwaizse-messageboard on 2023-10-31T08:37:27+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shahwaizse-messageboard"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
